<embed src="/MQTM_Mainv4_9.swf" 
flashvars="userGuid=1&modeStartup=1" 
wmode="transparent" 
id="MQTM_Main" 
quality="high" 
bgcolor="#ffffff" 
name="MQTM_Main" 
allowscriptaccess="sameDomain" 
pluginspage="http://web.archive.org/web/20090914220904/http://www.adobe.com/go/getflashplayer" 
type="application/x-shockwave-flash" 
width="1280" height="720" align="middle">